# Generated by Django 5.2.9 on 2025-12-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='created_by',
        ),
    ]
