# Generated by Django 5.2.9 on 2025-12-18 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_scheduledevent_lecturer_scheduledevent_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
