# Generated by Django 5.2.9 on 2025-12-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_course_year_scheduledevent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
