# Generated by Django 5.2.9 on 2025-12-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_major_course_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='title',
            field=models.CharField(default='New Event', max_length=255),
        ),
    ]
