# Generated by Django 5.2.9 on 2025-12-18 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_major_course_major'),
        ('users', '0002_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='calendar_app.major'),
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
