# Generated by Django 5.2.9 on 2025-12-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_major_course_major'),
        ('users', '0003_alter_studentprofile_major_delete_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='calendar_app.course'),
        ),
    ]
